# Change these first
owner: PuddiDuddi # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository
sites: # List of endpoints to track
  - name: Exchange Rates API
    url: https://exchangeapi.puddi.monster/status
    expectedStatusCodes:
      - 404
status-website: # Status website (optional)
  cname: status.puddi.monster
  name: Upptime # Status website title
  favicon: https://screens.puddi.monster/poopoo.ico
  css: ":root {
    --primary-color: #FFCC00; /* Bright yellow for main elements */
    --secondary-color: #603813; /* Dark brown for accents */
    --background-color: #FFF7DD; /* Light yellow for background */
    --text-color: #3D2B1F; /* Darker brown for text */
  }

  body {
    background-color: var(--background-color);
    color: var(--text-color);
    font-family: "Arial", sans-serif;
  }

  a {
    color: var(--primary-color);
    text-decoration: none;
  }

  a:hover {
    color: var(--secondary-color);
  }

  .navbar, .header {
    background-color: var(--primary-color);
    border-bottom: 3px solid var(--secondary-color);
    color: var(--text-color);
  }

  .footer {
    background-color: var(--secondary-color);
    color: var(--primary-color);
  }

  button, .btn {
    background-color: var(--primary-color);
    color: var(--text-color);
    border: 2px solid var(--secondary-color);
    padding: 0.5em 1em;
    border-radius: 5px;
  }

  button:hover, .btn:hover {
    background-color: var(--secondary-color);
    color: var(--primary-color);
  }

  .card {
    background-color: var(--primary-color);
    color: var(--text-color);
    border: 1px solid var(--secondary-color);
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    border-radius: 8px;
    padding: 1em;
  }

  .chart {
    background-color: var(--background-color);
    border: 2px solid var(--secondary-color);
    padding: 1em;
    border-radius: 10px;
  }"
