# Change these first
owner: PuddiDuddi # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository
sites: # List of endpoints to track
  - name: Exchange Rates API
    url: https://exchangeapi.puddi.monster/status
    expectedStatusCodes:
      - 404
status-website: # Status website (optional)
  cname: status.puddi.monster
  name: Upptime # Status website title
  favicon: https://screens.puddi.monster/poopoo.ico
  logoUrl: https://screens.puddi.monster/poopoo.ico
  themeUrl: https://screens.puddi.monster/style.css
